eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/  # Eureka Server URL
  instance:
    prefer-ip-address: true  # Use IP instead of hostname
    

